name: Publish docs

on: [push]

jobs:
  publish-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - name: Push API docs to GitHub Pages
        run: |
          npm ci
          npm run docs
          npm run build-storybook
          VERSION=7.6.0
          cd ..
          git clone https://react-storefront-community:${{ secrets.GITHUB_TOKEN }}@github.com/react-storefront-community/react-storefront-community.github.io.git
          git clone https://${{ secrets.MOOVWEB_GITHUB_USER }}:${{ secrets.MOOVWEB_GITHUB_TOKEN }}@github.com/moovweb/react-storefront-docs.git
          cd react-storefront-community.github.io
          git remote set-url origin https://react-storefront-community:${{ secrets.GITHUB_TOKEN }}@github.com/react-storefront-community/react-storefront-community.github.io.git
          git fetch
          git pull
          mkdir ${VERSION}
          mv ../react-storefront/.storybook/build ${VERSION}/storybook
          cp ../react-storefront/docs/build/modules.json ${VERSION}
          cp -r ../react-storefront-docs/guides ${VERSION}
          mv ${VERSION}/guides/guides.json ${VERSION}
          sed -i "$ s/$/,\n${VERSION}/" versions.csv
          git add -A
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -m "Docs for version ${VERSION}" -a
          git push -u origin
        env:
          GITHUB_TOKEN: ${{ secrets.MOOVWEB_GITHUB_TOKEN }}
